/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "TalmodWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "TalmoditApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
